### PR TITLE
Allow to detect image from non-manged memory (IntPtr)

### PR DESCRIPTION
**Pull request by zgabi**

### CODE REVIEW

**Comment by tinohager** [comment]
In which case are you using that?

**Comment by zgabi** [comment]
I have a video stream from a network camera.
Decoding the frames and converting to Argb array with FFMpeg. 
Then I'd like to detect the objects on that image without copying it.
Or what do you mean?

**Comment by tinohager** [comment]
We have a simular case. But in our case we receive a byte array. How did you move the images from ffmpeg to c#? You are use the ffmpeg binaries or a custom implementation?

**Comment by zgabi** [comment]
I'm usign FFMpeg.Autogen: https://github.com/Ruslan-B/FFmpeg.AutoGen

IntPtr imageBuffer = IntPtr.Zero; // allocated only once, it points to the allocated memory + bmp header size
var dstArray = new byte*[8];
var dstStrideArray = new int[1];

AVFrame* frame = null;
frame = av_frame_alloc();
while (avcodec_receive_frame(videoCodec, frame) >= 0)
{
    dstArray[0] = (byte*)imageBuffer.ToPointer();
    dstStrideArray[0] = av_image_get_linesize(targetFormat, width, 0);
    sws_scale(yuvToRgbCtx, frame->data, frame->linesize, 0, height, dstArray, dstStrideArray);

   // now the decompressed image is in imageBuffer
}

I can send you the souce code of the video decoder class to a private address if you need it.

**Comment by zgabi** [comment]
By the way, we are using your package in a .net core 3.0 project... it works, however it would be good to have a netstandard 2.0 vesrion.

**Comment by tinohager** [comment]
Okay great news, i have planned an update to .netstandard 2.0 :)
We have a c++ project with a namedpipe to transfer the vidoes of a rtsp stream to c#. In my case we have a byte array. Yes please send me your solution that i can test your pull. `tino.hager`📧`alturos.com`

**Comment by tinohager** [comment]
I have remove the ImageAnalyzer part i have some changes in the new version and i want merge the code the next weeks... Thanks for your help with the unit test

**Comment by zgabi** [comment]
Thank you very much.

ImageAnalyzer: Ok, I don't need that changes, just wanted to make consistent the detect code with the byte[] version. So for me the current version is perfect. Anyway, you can add that check or ignore it, as you wish.

Now (once it is released on nuget) I can use the official package instead of my "hacked" version:)

**Comment by tinohager** [comment]
I have push the new package https://www.nuget.org/packages/Alturos.Yolo/2.6.4

**Comment by tinohager** [comment]
@zgabi An other way to read frames from a stream https://github.com/nager/Nager.VideoStream

**Pull request closed without merging**
